### ISSUE TITLE
can you help me to solve this problem

### ISSUE THREAD

**Issue by wuzhuang5-zz** [marinkobabic/axon-kafka-example#2]
can you help me to solve this problem . thanks

**Comment by marinkobabic** [comment]
Are you using the example like it is including the docker-compose file for
the Kafka server?

**Comment by wuzhuang5-zz** [comment]
I didn't use docker. I used Kafka in this machine.

**Comment by wuzhuang5-zz** [comment]
I'll try.

**Comment by marinkobabic** [comment]
What is the actual issue? Producer does not work? Consumer does not work?
Please set the logging level to debug and send post the log of the
application here.

**Comment by wuzhuang5-zz** [comment]
* Where:
Build file '/Users/wz/IdeaProjects/axon-kafka-example/producer/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'producer'.
> Plugin with id 'com.palantir.docker' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by wuzhuang5-zz** [comment]
What social software do you use, can I add some questions to you? On axon framework

**Comment by wuzhuang5-zz** [comment]
thanks very much

**Comment by wuzhuang5-zz** [comment]
2018-08-26 19:59:59.201  INFO 2127 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-08-26 19:59:59.210 ERROR 2127 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at com.mykafka.producer.ProducerApplication.main(ProducerApplication.java:23) [classes/:na]
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:441) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:268) ~[kafka-clients-1.0.2.jar:na]
	at org.axonframework.kafka.eventhandling.producer.DefaultProducerFactory.createKafkaProducer(DefaultProducerFactory.java:161) ~[axon-kafka-3.3.2.jar:3.3.2]
	at org.axonframework.kafka.eventhandling.producer.DefaultProducerFactory.createTransactionalProducer(DefaultProducerFactory.java:145) ~[axon-kafka-3.3.2.jar:3.3.2]
	at org.axonframework.kafka.eventhandling.producer.DefaultProducerFactory.createProducer(DefaultProducerFactory.java:93) ~[axon-kafka-3.3.2.jar:3.3.2]
	at org.axonframework.kafka.eventhandling.producer.KafkaPublisher.send(KafkaPublisher.java:117) ~[axon-kafka-3.3.2.jar:3.3.2]
	at org.axonframework.eventhandling.AbstractEventBus.lambda$prepareCommit$15(AbstractEventBus.java:231) ~[axon-core-3.3.3.jar:3.3.3]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_171]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404) ~[na:1.8.0_171]
	at org.axonframework.eventhandling.AbstractEventBus.prepareCommit(AbstractEventBus.java:231) ~[axon-core-3.3.3.jar:3.3.3]
	at org.axonframework.eventhandling.AbstractEventBus.publish(AbstractEventBus.java:134) ~[axon-core-3.3.3.jar:3.3.3]
	at org.axonframework.eventhandling.EventBus.publish(EventBus.java:70) ~[axon-core-3.3.3.jar:3.3.3]
	at com.mykafka.producer.Sender.send(Sender.java:26) ~[classes/:na]
	at com.mykafka.producer.ProducerApplication.run(ProducerApplication.java:32) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	... 5 common frames omitted
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64) ~[kafka-clients-1.0.2.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:396) ~[kafka-clients-1.0.2.jar:na]
	... 19 common frames omitted

2018-08-26 19:59:59.211  INFO 2127 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7fa98a66: startup date [Sun Aug 26 19:59:22 CST 2018]; root of context hierarchy
2018-08-26 19:59:59.212  INFO 2127 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2018-08-26 19:59:59.213  INFO 2127 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -1073741824
2018-08-26 19:59:59.213  INFO 2127 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147482648
2018-08-26 19:59:59.215  INFO 2127 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown

**Comment by wuzhuang5-zz** [comment]
oh man The project worked. Thank you.

**Comment by wuzhuang5-zz** [comment]
i want to run it in one applicaiton.yml 
`axon:
    kafka:
      producer:defaulttopic: mydefaulttopic
      producer:
        retries: 5
        bootstrapservers:
           - 127.0.0.1:9092
        transaction-id-prefix: clxtrx
        client-id: myproducer
    eventhandling:
      processors:
        "[MyProcessor]":
          source: kafkaMessageSource
          mode: TRACKING
      clientid: myconsumer
      defaulttopic: mydefaulttopic
      consumer:
        group-id: boot
        bootstrapservers:
            - 127.0.0.1:9092`
Is this the right configuration? Thanks

**Comment by marinkobabic** [comment]
You would like to combine the two applications into one?

**Comment by wuzhuang5-zz** [comment]
yes,in one service.

**Comment by marinkobabic** [comment]
Have you been able to solve this problem?
